# Задание 1. Уровень доходов

Вы будете работать с широко известным набором данных по уровню дохода людей на основе данных переписи населения 1994 года в США (исходные данные тут http://www.cs.toronto.edu/~delve/data/adult/desc.html или тут https://www.kaggle.com/datasets/uciml/adult-census-income). Годовой доход человека зависит от различных факторов. На него влияет уровень образования человека, возраст, пол, род занятий и т. д. 

Переменные в датасете

- **age** - возраст, число.
- **workclass** - тип занятости, возможные значения: *Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked*.
- **fnlwgt** - вес, присвоенный бюро переписи населения США каждой строке, число.
- **education** - образование, возможные значения: *Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool*.
- **education-num** - число.
- **marital-status** - семейное положение, возможные значения: *Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.*
- **occupation** - тип профессии, возможные значения: *Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.*
- **relationship** - отношения, возможные значения:  *Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried*.
- **race** - раса, возможные значения: *White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.*
- **sex** - пол, возможные значения:  *Female, Male*.
- **capital-gain** - прирост капитала, число.
- **capital-loss** - прирост капитала, число.
- **hours-per-week** - занятость, часов в неделю, число.
- **native-country** - родная страна, возможные значения: *United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands*.   
- **salary** - годовой доход, возможные значения : *>50K,<=50K*

Ответьте на ниже следующие вопросы, аргументируя ответы выполненным программным кодом.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/ASUDYK/SDA/main/data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  str
 14  salary          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [26]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Male,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Male,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Male,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Male,15024,0,40,United-States,>50K

**1. Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?**

In [28]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст (признак *age*) женщин?**

In [32]:
data[data['sex'] == 'Female']['age'].mean()

np.float64(36.85823043357163)

**3. Какова доля рожденных в Германии (признак *native-country*)?**

In [6]:
(data['native-country'] == 'Germany').mean()

np.float64(0.004207487485028101)

**4-5. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год?**

In [53]:
print(data[data['salary'] == '>50K']['age'].mean())
print(data[data['salary'] == '>50K']['age'].std())

print(data[data['salary'] == '<=50K']['age'].mean())
print(data[data['salary'] == '<=50K']['age'].std())

44.24984058155847
10.519027719851826
36.78373786407767
14.02008849082488

**6. Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [9]:
# не правда
ed = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
data[data['salary'] == '>50K']['education'].isin(ed).all()

np.False_

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [10]:
group = data.groupby(['race', 'sex'])['age'].describe()
print(group)
group.loc[("Amer-Indian-Eskimo", "Male"), "max"]

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

np.float64(82.0)

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [53]:
# женатых, зарабатывающих больше 50К, больше
men = data[data['sex'] == 'Male'].copy()
men['married'] = men['marital-status'].str.startswith('Married')
men['rich'] = men['salary'] == '>50K'
men.groupby('married')['rich'].mean()

married
False    0.084495
True     0.440514
Name: rich, dtype: float64

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое (максимальное) количество часов, и каков среди них процент зарабатывающих много?**

In [ ]:
# Ваш код здесь

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) выходцев для каждой страны (*native-country*).**

In [ ]:
# Ваш код здесь

# Задание 2. Олимпийские игры

Вы будете анализировать исторический набор данных об Олимпийских играх, включая все Игры с 1896 года в Афинах до Игр в Рио-де-Жанейро в 2016 году (исходные данные тут https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results). Обратите внимание, что Зимние и Летние игры проводились в один и тот же год вплоть до 1992 года. После этого они были распределены  в четырехлетнем цикле, начиная с 1994 года - зимние, затем летние в 1996 году, затем зимние в 1998 году и так далее. Распространенная ошибка, которую допускают при анализе этих данных, состоит в том, что исследователи предполагают, что Летние и Зимние игры всегда проходили в шахматном порядке.

Каждая строка соответствует отдельному спортсмену, участвующему в отдельном олимпийском соревновании. Столбцы:
- __ID__ - уникальный номер для каждого спортсмена
- __Name__ - имя спортсмена
- __Sex__ - пол M or F
- __Age__ - возраст в годах
- __Height__ - рост в сантиметрах
- __Weight__ - масса в килограммах
- __Team__ - Команда
- __NOC__ - трехбуквенный код Национального олимпийского комитета
- __Games__ - год Олимпиады и сезон (зима/лето)
- __Year__ - год
- __Season__ - сезон (зима/лето)
- __City__ - принимающий Олимпиаду город
- __Sport__ - вид спорта
- __Event__ - событие
- __Medal__ - медальный статус, возможные значения *Gold, Silver, Bronze, NA*

Ответьте на ниже следующие вопросы, аргументируя ответы выполненным программным кодом.

In [ ]:
import pandas as pd

In [ ]:
PATH = 'https://github.com/ASUDYK/SDA/blob/main/data/athlete_events.csv.zip?raw=true'

__0. Откройте файл и отобразите первые 20 строк датасета, используя необходимые параметры и не меняя переменную PATH__

In [ ]:
# ваш код

__1. Сколько лет было самым молодым участникам Олимпийских игр 1992 года (мужчинам и женщинам)?__
- 16 и 15
- 14 и 13 
- 13 и 11
- 11 и 12

In [ ]:
# ваш код

__2. Каков был процент баскетболистов-мужчин среди всех мужчин-участников Олимпийских игр 2012 года? Округлите ответ до первого десятичного знака.__

Здесь и далее при необходимости отбрасывайте дубликаты, чтобы учитывать только уникальных спортсменов. 
- 0.2
- 1.5 
- 2.5
- 7.7

In [ ]:
# ваш код

__3. Каковы среднее значение и стандартное отклонение роста теннисисток, участвовавших в Олимпийских играх 2000 года? Округлите ответ до первого десятичного знака.__

- 171.8 и 6.5
- 179.4 и 10
- 180.7 и 6.7
- 182.4 и 9.1

In [4]:
# ваш код

__4. Найдите спортсмена, который участвовал в Олимпийских играх 2006 года, с наибольшей массой тела среди всех участников той же Олимпиады. Каким спортом он или она занимался?__

- Дзюдо (Judo)
- Бобслей (Bobsleigh) 
- Скелетон (Skeleton)
- Бокс (Boxing)

In [ ]:
# ваш код

__5. Сколько раз Джон Ольберг (John Aalberg) участвовал в Олимпийских играх в разные годы?__

Одна Олимпиада - это один раз. Неважно сколько соревнований в ходе Олимпиады было
- 0
- 1 
- 2
- 3

In [ ]:
# ваш код

__6. Сколько золотых медалей по теннису выиграли спортсмены сборной Швейцарии (Switzerland) на Олимпиаде-2008? Считайте каждую медаль от каждого спортсмена.__

- 0
- 1 
- 2
- 3

In [ ]:
# ваш код

__7. Правда ли, что на Олимпийских играх 2016 Испания выиграла меньше медалей, чем Италия?__ 

- Да
- Нет

In [ ]:
# ваш код

__8. К какой возрастной категории принадлежало наименьшее и наибольшее количество участников Олимпиады-2008?__

- [45-55] и [25-35) соответственно
- [45-55] и [15-25) соответственно
- [35-45) и [25-35) соответственно
- [45-55] и [35-45) соответственно

In [ ]:
# ваш код

__9. Правда ли, что в Москве проводились летние Олимпийские игры? Правда ли, что в Скво-Вэлли (Squaw Valley) проводились зимние Олимпийские игры?__

- Да, Да
- Да, Нет
- Нет, Да 
- Нет, Нет

In [ ]:
# ваш код

__10. Какова абсолютная разница между количеством уникальных видов спорта на Олимпиаде 1986 года и Олимпиаде 2002 года?__

- 3 
- 10
- 15
- 27

In [ ]:
# ваш код